
// Generated by Cadence Encounter(R) RTL Compiler RC14.12 - v14.10-s022_1

module flipflop_1_100(CLK, D, Q);
  input CLK, D;
  output Q;
  wire CLK, D;
  wire Q;
  fflopd Q_reg(.CK (CLK), .D (D), .Q (Q));
endmodule

