
// Generated by Cadence Encounter(R) RTL Compiler RC14.12 - v14.10-s022_1

module mux_2_1_100(C, A_00, A_01, Z);
  input [1:0] C;
  input A_00, A_01;
  output Z;
  wire [1:0] C;
  wire A_00, A_01;
  wire Z;
  wire n_0, n_1;
  nand2 g42(.A (n_1), .B (n_0), .Y (Z));
  nand2 g43(.A (C[0]), .B (A_00), .Y (n_1));
  nand2 g44(.A (C[1]), .B (A_01), .Y (n_0));
endmodule

