
// Generated by Cadence Encounter(R) RTL Compiler RC14.12 - v14.10-s022_1

module unary_or_2_100(A, Z);
  input [1:0] A;
  output Z;
  wire [1:0] A;
  wire Z;
  wire n_0, n_1;
  nand2 g4(.A (n_0), .B (n_1), .Y (Z));
  inv1 g5(.A (A[0]), .Y (n_1));
  inv1 g6(.A (A[1]), .Y (n_0));
endmodule

